server:
  port: 8008
spring:
  application:
    name: cheque-processor
  datasource:
    url: jdbc:h2:file:./data/mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
